name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unixpublish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.103
    - name: Linux Publish
      run: |
        GIT_HASH=$(git rev-parse --short $GITHUB_SHA)
        git submodule sync
        git submodule update
        dotnet publish OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --configuration Release --runtime linux-x64 --framework netcoreapp3.1 --version-suffix "$GIT_HASH"
        dotnet publish OpenTabletDriver.Daemon/OpenTabletDriver.Daemon.csproj --configuration Release --runtime linux-x64 --framework netcoreapp3.1 --version-suffix "$GIT_HASH"
        dotnet publish OpenTabletDriver.Console/OpenTabletDriver.Console.csproj --configuration Release --runtime linux-x64 --framework netcoreapp3.1 --version-suffix "$GIT_HASH"
    - name: Copy configurations
      run: |
        cp -vr ./TabletDriverLib/Configurations/ ./OpenTabletDriver.Daemon/bin/Release/netcoreapp3.1/linux-x64/publish
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: OpenTabletDriver linux-x64
        path: ./**/bin/Release/netcoreapp3.1/linux-x64/publish

  windowspublish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.103
      - name: Windows Publish
        run: |
          $GIT_HASH = $(git rev-parse --short ${ENV:GITHUB_SHA})
          git submodule sync
          git submodule update
          dotnet publish OpenTabletDriver.UX.Wpf/OpenTabletDriver.UX.Wpf.csproj --configuration Release --runtime win-x64 --framework netcoreapp3.1 --version-suffix "$GIT_HASH"
          dotnet publish OpenTabletDriver.Daemon/OpenTabletDriver.Daemon.csproj --configuration Release --runtime win-x64 --framework netcoreapp3.1 --version-suffix "$GIT_HASH"
          dotnet publish OpenTabletDriver.Console/OpenTabletDriver.Console.csproj --configuration Release --runtime win-x64 --framework netcoreapp3.1 --version-suffix "$GIT_HASH"
      - name: Copy configurations
        run: Copy-Item -Path "./TabletDriverLib/Configurations/" -Destination "./OpenTabletDriver.Daemon/bin/Release/netcoreapp3.1/win-x64/publish/Configurations/" -Recurse
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@master
        with:
          name: OpenTabletDriver win-x64
          path: ./**/bin/Release/netcoreapp3.1/win-x64/publish
